fix: switch branch

diff --git a/.github/workflows/tagpr.yml b/.github/workflows/tagpr.yml
--- a/.github/workflows/tagpr.yml
+++ b/.github/workflows/tagpr.yml
@@ -33,13 +33,27 @@ jobs:
           go-version-file: go.mod
 
       - uses: Songmu/tagpr@812f0c28980cb9a1e5cf427b65c1ac6a1d2b4377 # v1.6.1
+        id: tagpr
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       # tagpr guess version from label, but we need to guess it from conventional commit.
       - name: Get next version from svu
         id: svu
-        run: 'echo next="$(go run github.com/caarlos0/svu/v3@latest next)" >> "$GITHUB_OUTPUT"'
+        run: |
+          next_version=$(go run github.com/caarlos0/svu/v3@latest next)
+          if [ $? -ne 0 ]; then
+            echo "::error::Failed to get the next version using svu"
+            exit 1
+          fi
+          echo "next=$next_version" >> "$GITHUB_OUTPUT"
+
+      - name: Switch to PR
+        run: |
+          PR_NUMBER=$(jq -r '.number' ${{ steps.tagpr.outputs.pull_request }})
+          gh pr checkout "$PR_NUMBER"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Edit version file and commit and push
         run: |
